url: "https://sethjsa.github.io"
baseurl: ""
title: "Seth Aycock"
permalink: /blog/:title/
encoding: "utf-8"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - "*.sublime-project"
  - "*.sublime-workspace"
