url: "https://sethjsa.github.io"
baseurl: ""
title: "Seth Aycock"
future: true
encoding: "utf-8"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - "*.sublime-project"
  - "*.sublime-workspace"
