#!/usr/bin/env python3
"""Import all-time top-rated films from a local Letterboxd data export.

Letterboxd has no public API for full watch history (only a manual
developer-approval process), so this reads a manual export instead:
on letterboxd.com go to Settings -> Import & Export -> Export Your Data,
then run this script against the downloaded zip. It computes the
all-time top-rated films and writes _data/letterboxd_ratings.yml.

This is NOT automated - re-run it by hand whenever you want to refresh
the all-time top-rated list from a fresh export. The "recently logged"
list is separate and handled by scripts/update_letterboxd_recent.py,
which IS automated (reads the public RSS feed, no export needed).

Usage:
    python scripts/import_letterboxd_export.py path/to/letterboxd-export.zip
"""
import csv
import io
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "_data" / "letterboxd_ratings.yml"

TOP_N = 5


def main():
    if len(sys.argv) != 2:
        print("Usage: python scripts/import_letterboxd_export.py path/to/export.zip", file=sys.stderr)
        sys.exit(1)

    with zipfile.ZipFile(sys.argv[1]) as z:
        with z.open("ratings.csv") as f:
            rows = list(csv.DictReader(io.TextIOWrapper(f, encoding="utf-8")))

    for r in rows:
        r["Rating"] = float(r["Rating"])

    # Highest rating first, most-recently-rated first among ties.
    rows.sort(key=lambda r: (r["Rating"], r["Date"]), reverse=True)
    top = rows[:TOP_N]

    out = {
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "total_rated": len(rows),
        "average_rating": round(sum(r["Rating"] for r in rows) / len(rows), 2),
        "top_rated": [
            {
                "name": r["Name"],
                "year": int(r["Year"]) if r["Year"] else None,
                "rating": r["Rating"],
                "date": r["Date"],
                "url": r["Letterboxd URI"],
            }
            for r in top
        ],
    }
    with open(DATA_FILE, "w") as f:
        f.write("# Generated by scripts/import_letterboxd_export.py from a manual\n")
        f.write("# Letterboxd data export - re-run by hand to refresh, not automated.\n")
        yaml.dump(out, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {DATA_FILE} ({len(top)} top-rated films from {len(rows)} total ratings)")


if __name__ == "__main__":
    main()
