#!/usr/bin/env python3
"""Import top-rated albums from a local RateYourMusic data export.

RateYourMusic has no public API and its RSS feed sits behind Cloudflare
bot protection that a script can't reliably get past, so this reads a
manual export instead: on rateyourmusic.com go to Profile -> Data Export
(or similar), download the ratings/collection CSV, and run this script
against it. That export has no per-item rating date, so it can only
support an all-time "top rated" list, not a "recently rated" one - same
split as Letterboxd's top_rated (import_letterboxd_export.py) vs.
recent (update_letterboxd_recent.py, which reads a public RSS feed RYM
doesn't offer an equivalent of).

Album artwork isn't in the export either, so this looks each top album
up on iTunes's public search API (no key required) to get cover art and
a link out.

This is NOT automated - re-run it by hand whenever you want to refresh
the top-rated list from a fresh export.

Usage:
    python scripts/import_rym_export.py path/to/export.csv
"""
import csv
import html
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "_data" / "rym_ratings.yml"

TOP_N = 5
ITUNES_SEARCH_URL = "https://itunes.apple.com/search"


def lookup_artwork(artist, title):
    params = {"term": f"{artist} {title}", "media": "music", "entity": "album", "limit": 1}
    url = f"{ITUNES_SEARCH_URL}?{urllib.parse.urlencode(params)}"
    req = urllib.request.Request(url, headers={"User-Agent": "sethjsa.github.io stats script"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        print(f"  iTunes lookup failed for {artist} - {title}: {e!r}", file=sys.stderr)
        return None, None
    results = data.get("results") or []
    if not results:
        return None, None
    r = results[0]
    # artworkUrl100 -> swap in a bigger size, standard iTunes Search API trick.
    artwork = (r.get("artworkUrl100") or "").replace("100x100", "600x600") or None
    return artwork, r.get("collectionViewUrl")


def main():
    if len(sys.argv) != 2:
        print("Usage: python scripts/import_rym_export.py path/to/export.csv", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1], newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    albums = []
    for r in rows:
        rating = r.get("Rating")
        if not rating:
            continue
        artist = html.unescape(f'{r.get(" First Name", r.get("First Name", "")).strip()} {r.get("Last Name", "").strip()}'.strip())
        rating = int(rating)
        albums.append({
            "artist": artist,
            "name": html.unescape(r["Title"].strip()),
            "year": int(r["Release_Date"]) if r.get("Release_Date") else None,
            "rating": rating,
            # RYM's 1-10 scale is really 0.5-5 stars underneath (same scale
            # Letterboxd uses) - shown as stars to match that widget exactly.
            "stars": rating / 2.0,
        })

    albums.sort(key=lambda a: a["rating"], reverse=True)
    top = albums[:TOP_N]

    for a in top:
        image, url = lookup_artwork(a["artist"], a["name"])
        a["image"] = image
        a["url"] = url
        time.sleep(0.5)

    out = {
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "total_rated": len(albums),
        "average_rating": round(sum(a["rating"] for a in albums) / len(albums), 2) if albums else 0,
        "top_rated": top,
    }
    with open(DATA_FILE, "w") as f:
        f.write("# Generated by scripts/import_rym_export.py - not automated, re-run by hand against a fresh export.\n")
        yaml.dump(out, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {DATA_FILE} ({len(albums)} rated albums, top {len(top)})", file=sys.stderr)


if __name__ == "__main__":
    main()
