#!/usr/bin/env python3
"""Pull recently logged films from Letterboxd's public RSS feed.

Letterboxd has no public API for full watch history, but the diary RSS
feed (public, no auth) covers the ~50 most recent logged films with
rich metadata (rating, watched date, poster, review snippet). This
writes that to _data/letterboxd_recent.yml.

For all-time top-rated films (which need full history, not just the
RSS window), see scripts/import_letterboxd_export.py instead - that
one requires a manual data export and isn't automated.

Usage:
    python scripts/update_letterboxd_recent.py
"""
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "_data" / "letterboxd_recent.yml"

RSS_URL = "https://letterboxd.com/ducksalad/rss/"
NS = {"letterboxd": "https://letterboxd.com"}

IMG_RE = re.compile(r'<img src="([^"]+)"')
KEEP = 12


def fetch_rss():
    req = urllib.request.Request(RSS_URL, headers={"User-Agent": "sethjsa.github.io stats script"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_items(xml_bytes):
    root = ET.fromstring(xml_bytes)
    items = []
    for item in root.findall(".//item"):
        title_el = item.find("letterboxd:filmTitle", NS)
        year_el = item.find("letterboxd:filmYear", NS)
        rating_el = item.find("letterboxd:memberRating", NS)
        watched_el = item.find("letterboxd:watchedDate", NS)
        rewatch_el = item.find("letterboxd:rewatch", NS)
        link_el = item.find("link")
        desc_el = item.find("description")

        poster = None
        if desc_el is not None and desc_el.text:
            m = IMG_RE.search(desc_el.text)
            if m:
                poster = m.group(1)

        items.append({
            "name": title_el.text if title_el is not None else None,
            "year": int(year_el.text) if year_el is not None and year_el.text else None,
            "rating": float(rating_el.text) if rating_el is not None and rating_el.text else None,
            "watched_date": watched_el.text if watched_el is not None else None,
            "rewatch": (rewatch_el.text == "Yes") if rewatch_el is not None else False,
            "url": link_el.text if link_el is not None else None,
            "poster": poster,
        })
    return items


def main():
    xml_bytes = fetch_rss()
    items = parse_items(xml_bytes)
    items.sort(key=lambda i: i["watched_date"] or "", reverse=True)

    out = {
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "recent": items[:KEEP],
    }
    with open(DATA_FILE, "w") as f:
        f.write("# Auto-generated by scripts/update_letterboxd_recent.py - do not hand-edit.\n")
        yaml.dump(out, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {DATA_FILE} ({len(out['recent'])} recent films)", file=sys.stderr)


if __name__ == "__main__":
    main()
