#!/usr/bin/env python3
"""Pull recently read books from Goodreads' private shelf RSS feed.

Goodreads' RSS export for a shelf includes per-book rating and read
date but no official public API for this anymore, so the RSS feed
(with a private key baked into the URL) is the only automatable
source. This writes the 10 most recently read books (by user_read_at)
to _data/goodreads_recent.yml.

Set the full feed URL (including the key= param) as the
GOODREADS_RSS_URL environment variable / GitHub secret, e.g.:
https://www.goodreads.com/review/list_rss/<user_id>?key=<key>&shelf=read

Usage:
    GOODREADS_RSS_URL=... python scripts/update_goodreads_recent.py
"""
import os
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "_data" / "goodreads_recent.yml"

KEEP = 10


def fetch_rss():
    url = os.environ["GOODREADS_RSS_URL"]
    req = urllib.request.Request(url, headers={"User-Agent": "sethjsa.github.io stats script"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_items(xml_bytes):
    root = ET.fromstring(xml_bytes)
    items = []
    for item in root.findall(".//item"):
        title_el = item.find("title")
        author_el = item.find("author_name")
        rating_el = item.find("user_rating")
        read_at_el = item.find("user_read_at")
        book_id_el = item.find("book_id")
        cover_el = item.find("book_large_image_url")

        read_at = read_at_el.text if read_at_el is not None else None
        if not read_at:
            continue

        rating = int(rating_el.text) if rating_el is not None and rating_el.text else 0
        book_id = book_id_el.text if book_id_el is not None else None

        items.append({
            "title": title_el.text if title_el is not None else None,
            "author": author_el.text if author_el is not None else None,
            "rating": rating or None,
            "read_at": parsedate_to_datetime(read_at).strftime("%Y-%m-%d"),
            "url": f"https://www.goodreads.com/book/show/{book_id}" if book_id else None,
            "cover": cover_el.text if cover_el is not None else None,
        })
    return items


def main():
    xml_bytes = fetch_rss()
    items = parse_items(xml_bytes)
    items.sort(key=lambda i: i["read_at"], reverse=True)

    out = {
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "recent": items[:KEEP],
    }
    with open(DATA_FILE, "w") as f:
        f.write("# Auto-generated by scripts/update_goodreads_recent.py - do not hand-edit.\n")
        yaml.dump(out, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {DATA_FILE} ({len(out['recent'])} recent books)", file=sys.stderr)


if __name__ == "__main__":
    main()
